# 社区插件合集
src-git kenzo https://github.com/kenzok8/openwrt-packages.git^097c741518adebf2c64fc1d533fdb46d3bcd22c0

# @override kenzo luci-theme-argon
# @override kenzo luci-app-argon-config
# @config CONFIG_PACKAGE_luci-theme-argon=y
# @config CONFIG_PACKAGE_luci-app-argon-config=y

# 代理插件库 (包含 sing-box)
src-git passwall_packages https://github.com/Openwrt-Passwall/openwrt-passwall-packages.git^77110414008c0985d29267fa03be80b8293cd508

# @override passwall_packages sing-box
# @config CONFIG_PACKAGE_sing-box=y
# @config CONFIG_SING_BOX_BUILD_QUIC=y
# @config CONFIG_SING_BOX_BUILD_UTLS=y
# @config CONFIG_SING_BOX_BUILD_WIREGUARD=y
# @config CONFIG_SING_BOX_BUILD_CLASH_API=y
# @config CONFIG_SING_BOX_BUILD_DHCP=y
# @config CONFIG_SING_BOX_BUILD_ACME=y
# @config CONFIG_SING_BOX_BUILD_GVISOR=y
# @config CONFIG_SING_BOX_BUILD_TAILSCALE=y
