# arch: aarch64_cortex-a53
# ib-url:  https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/openwrt-imagebuilder-mediatek-filogic.Linux-x86_64.tar.zst
# sdk-url: https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/openwrt-sdk-mediatek-filogic_gcc-14.3.0_musl.Linux-x86_64.tar.zst
# GL.iNet GL-MT3600BE (MT7988 + MT7990 Wi-Fi 7)

CONFIG_TARGET_mediatek=y
CONFIG_TARGET_mediatek_filogic=y
CONFIG_TARGET_mediatek_filogic_DEVICE_glinet_gl-mt3600be=y

CONFIG_LUCI_LANG_zh_Hans=y
